### ISSUE TITLE
Having Issue with drawer navigation

### ISSUE THREAD

**Issue by riyas145** [bortolilucas/react-native-jitsimeet#21]
reanimated 
gesture handler having issue

**Comment by bortolilucas** [comment]
Have you tried matching your package versions with Jitsi Meet's? They still use version 1 of reanimated

https://github.com/jitsi/jitsi-meet/blob/master/package.json

**Comment by riyas145** [comment]
After Removing reanimated plugin also having same issue there is any cache need to clean ? i have tried all the possible ways

**Comment by bortolilucas** [comment]
The fact Jitsi Meet SDK is a packed RN SDK that is built alongside your RN app makes it super buggy, sadly

try `cd android && ./gradlew clean` or try to delete your local project folder and refetch it from the repository

**Comment by riyas145** [comment]
Yes @bortolilucas  i have tried that also when i was checking android studio log that has showing reanimated erros only

"dependencies": {
    "@anatolyk/react-native-week-view": "^1.0.8",
    "@react-native-async-storage/async-storage": "^1.15.15",
    "@react-native-community/slider": "^4.2.0",
    "@react-native-google-signin/google-signin": "^7.0.4",
    "@react-navigation/bottom-tabs": "^6.2.0",
    "@react-navigation/drawer": "^6.3.3",
    "@react-navigation/material-top-tabs": "^6.1.1",
    "@react-navigation/native": "^6.0.0",
    "@react-navigation/native-stack": "^6.2.5",
    "axios": "^0.26.0",
    "formik": "^2.2.9",
    "jwt-decode": "^3.1.2",
    "react": "17.0.2",
    "react-native": "0.66.4",
    "react-native-date-picker": "^4.1.3",
    "react-native-document-picker": "^8.0.0",
    "react-native-fbsdk-next": "^7.0.1",
    "react-native-flash-message": "^0.2.1",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-image-picker": "^4.7.3",
    "react-native-orientation-locker": "^1.4.0",
    "react-native-pager-view": "^5.4.11",
    "react-native-paper": "^4.11.2",
    "react-native-push-notification": "^8.1.1",
    "react-native-raw-bottom-sheet": "^2.2.0",
    "react-native-reanimated": "^2.5.0",
    "react-native-render-html": "^6.3.4",
    "react-native-s3-upload": "^0.0.12",
    "react-native-safe-area-context": "^3.0.2",
    "react-native-screens": "^3.13.1",
    "react-native-simple-toast": "^1.1.3",
    "react-native-tab-view": "^3.1.1",
    "react-native-vector-icons": "^9.1.0",
    "react-native-video": "^5.2.0",
    "react-redux": "^7.2.6",
    "redux": "^4.1.2",
    "redux-thunk": "^2.4.1",
    "rn-fetch-blob": "^0.12.0",
    "yup": "^0.32.11"
  }
  
  now i'm using reanimated latest version when i downgrade to jitsi version 1.13.3 also same issue happen please help me regarding this

**Comment by riyas145** [comment]
@bortolilucas  it may happen while other plugins used the latest reanimated plugins? how can i identify that ?

**Comment by bortolilucas** [comment]
What are the errors? Can you please show me the error log?

**Comment by riyas145** [comment]
2022-04-12 09:47:19.345 24577-24713/com.i2global I/ReactNativeJS: '2022-04-12T04:17:19.344Z', '[modules/browser/BrowserCapabilities.js]', 'This appears to be react-native, ver: 0.66.4'
2022-04-12 09:47:20.104 24577-24713/com.i2global W/ReactNativeJS: new NativeEventEmitter() was called with a non-null argument without the required addListener method.
2022-04-12 09:47:20.104 24577-24713/com.i2global W/ReactNativeJS: new NativeEventEmitter() was called with a non-null argument without the required removeListeners method.
2022-04-12 09:47:20.234 24577-24692/com.i2global E/ion: ioctl c0044901 failed with code -1: Invalid argument
2022-04-12 09:47:20.235 24577-24692/com.i2global D/SoLoader: About to load: libnative-imagetranscoder.so
2022-04-12 09:47:20.235 24577-24692/com.i2global D/SoLoader: libnative-imagetranscoder.so found on /data/data/com.i2global/lib-main
2022-04-12 09:47:20.236 24577-24692/com.i2global D/SoLoader: Loading lib dependencies: [liblog.so, libc.so, libm.so, libdl.so]
2022-04-12 09:47:20.237 24577-24692/com.i2global D/SoLoader: Loaded: libnative-imagetranscoder.so
2022-04-12 09:47:20.236 24577-24577/com.i2global W/FrescoIoBoundEx: type=1400 audit(0.0:2249943): avc: granted { execute } for path="/data/data/com.i2global/lib-main/libnative-imagetranscoder.so" dev="dm-11" ino=194923 scontext=u:r:untrusted_app:s0:c81,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c81,c258,c512,c768 tclass=file app=com.google.android.gms
2022-04-12 09:47:20.504 24577-24577/com.i2global D/DecorView[]: getWindowModeFromSystem windowmode is 1
2022-04-12 09:47:20.505 24577-24716/com.i2global I/JitsiMeetSDK: AudioMode Update audio route for mode: 0
2022-04-12 09:47:20.506 24577-24716/com.i2global I/JitsiMeetSDK: AudioMode Updating audio device list
2022-04-12 09:47:20.509 24577-24714/com.i2global I/JitsiMeetSDK: [features/base/connection] No connection found while disconnecting.
2022-04-12 09:47:20.530 24577-24714/com.i2global D/JitsiMeetSDK: ExternalAPI Sending event: VIDEO_MUTED_CHANGED with data: { NativeMap: {"muted":0} }
2022-04-12 09:47:20.544 24577-24714/com.i2global I/JitsiMeetSDK: [features/base/net-info] Network changed {"isOnline":true,"details":{"isConnectionExpensive":false,"subnet":"255.255.255.255","ipAddress":"192.168.29.248","frequency":2462,"strength":99,"bssid":"02:00:00:00:00:00"},"networkType":"wifi"}
2022-04-12 09:47:20.544 24577-24714/com.i2global D/JitsiMeetSDK: [modules/connectivity/NetworkInfo.js] updateNetworkInfo { isOnline: true }
2022-04-12 09:47:20.557 24577-24826/com.i2global I/System.out: [socket]:check permission begin!
2022-04-12 09:47:20.650 24577-24714/com.i2global E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
Process: com.i2global, PID: 24577
com.facebook.react.bridge.NativeArgumentsParseException: RNGestureHandlerModule.attachGestureHandler got 3 arguments, expected 2
at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:349)
at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
at android.os.Looper.loop(Looper.java:236)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
at java.lang.Thread.run(Thread.java:923)
2022-04-12 09:47:20.653 24577-24714/com.i2global D/OOMEventManagerFK: checkEventAndDumpForJE: 0
2022-04-12 09:47:20.660 24577-24714/com.i2global E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
com.facebook.react.bridge.NativeArgumentsParseException: RNGestureHandlerModule.attachGestureHandler got 3 arguments, expected 2
at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:349)
at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
at android.os.Looper.loop(Looper.java:236)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
at java.lang.Thread.run(Thread.java:923)

com.facebook.react.bridge.NativeArgumentsParseException: RNGestureHandlerModule.attachGestureHandler got 3 arguments, expected 2
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:349)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
    at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
    at android.os.Looper.loop(Looper.java:236)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
    at java.lang.Thread.run(Thread.java:923)
    
    @bortolilucas

**Comment by riyas145** [comment]
@bortolilucas  please check this error log

**Comment by socialcode-rob1** [comment]
Its dependency version issue with react-native-gesture-handler and react-native-reanimated.
See https://github.com/bortolilucas/react-native-jitsimeet/issues/4#issuecomment-1099670691

Your project is conflicting with the dependencies the main jitsi-meet project is using.
